[project]
name = "syn-city"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "redis>=7.1.0",
    "sentence-transformers>=5.2.0",
]
